version: "3"
services:
    mysql:
        build: ./mysql
        container_name: mysql
        volumes:
            - ./mysql/db:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pw
            MYSQL_DATABASE: pre_app_db
            MYSQL_USER: gopher
            MYSQL_PASSWORD: setsetset
        networks:
            - pre_app_network
        ports:
            - "33060:3306"
    go_app:
        build: ./go
        container_name: go_app
        networks:
            - pre_app_network
        ports:
            - "8808:80"
        depends_on:
            - mysql
        environment:
            WAIT_HOSTS: mysql
    vue:
        build: ./vue
        container_name: vue
        volumes:
            - ./vue:/app
        working_dir: /app
        ports:
            - "8080:8080"
        command:
            - "yarn"
            - "serve"
        stdin_open: true
        tty: true
        # environment:
        # WAIT_HOSTS: go_app

networks:
    pre_app_network:
        external: true
